
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: tetris-ever
  version: '20.21.02.06' # just for humans, typically '1.2+git' or '1.3.2'
  summary: a simple tetris game writen with C, and render by SDL2. # 79 char long summary
  description: |
    **available key control for pure keyboard:**
    * Esc - Quit current scenes.
    * Q - Same as above.
    * up - rotate rock.
    * down - control rock fall down.
    * left - control rock to left.
    * right - control rock to right.

    _More detail please view code: < https://github.com/Joker2770/Tetris-ever >. _

  # icon: snap/gui/icon.png

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots
  base: core18
  
  apps:
    tetris-ever:
      command: usr/local/bin/Tetris-ever
      # desktop: tetris-ever.desktop
      plugs:
        - desktop
        - desktop-legacy
        - wayland
        - unity7
        # - opengl
        
  layout:
    /usr/local/bin/bb3273.ttf:
      bind-file: $SNAP/usr/local/bin/bb3273.ttf
    
  parts:
    tetris-ever:
      # after:
        # - desktop-glib-only
      plugin: cmake
      source: "https://github.com/Joker2770/Tetris-ever.git"
      source-depth: 1
      source-branch: main
      source-type: git
      build-packages:
        - gcc
        - g++
        - cmake
        - make
        - libsdl2-dev
        - libsdl2-ttf-dev
  
      stage-packages:
        - libsdl2-2.0-0
        - libsdl2-ttf-2.0-0
        # - libgl1-mesa-glx
        # - libglu1-mesa
